<!DOCTYPE html>
<html>
    <head>
        
        <title><?php echo $this->controller->title; ?></title>
        
        <!-- core resources and meta -->            
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <!--[if lt IE 9]>
            <script src="<?php echo \BASE_URL; ?>resources/core/bootstrap/js/html5shiv.min.js"></script>
            <script src="<?php echo \BASE_URL; ?>resources/core/bootstrap/js/respond.min.js"></script>
        <![endif]-->
        
        <link rel="stylesheet" type="text/css" href="<?php echo \BASE_URL; ?>resources/core/bootstrap/css/bootstrap.min.css"/>
        
        <script type="text/javascript" src="<?php echo \BASE_URL; ?>resources/core/jquery-1.11.2.min.js"></script>
        <script type="text/javascript" src="<?php echo \BASE_URL; ?>resources/core/bootstrap/js/bootstrap.min.js"></script>
        
        <!-- Stylesheets -->
        <?php \flat\CssLoader::load(); ?>
        
    </head>
    <body>
        
        $content$
        
        <!-- Javascript -->
        <?php \flat\JsLoader::load(); ?>
        
    </body>
</html>
